[package]
name = "blitz-py-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
blitz-dom = { git = "https://github.com/DioxusLabs/blitz", rev = "01a6c4b9282c25b76616d71863ea55a03c48a730", default-features = false, features = ["svg", "woff"] }
blitz-html = { git = "https://github.com/DioxusLabs/blitz", rev = "01a6c4b9282c25b76616d71863ea55a03c48a730" }
blitz-paint = { git = "https://github.com/DioxusLabs/blitz", rev = "01a6c4b9282c25b76616d71863ea55a03c48a730" }
blitz-traits = { git = "https://github.com/DioxusLabs/blitz", rev = "01a6c4b9282c25b76616d71863ea55a03c48a730" }
anyrender = "0.13"
anyrender_vello_cpu = "0.16"

[[bin]]
name = "render"
path = "fuzz_targets/render.rs"
test = false
doc = false
bench = false
